canal:
    client:
        instances:
            example:
                host: 127.0.0.1
                port: 11111
                batchSize: 100
                userName: canal
                password: admin
                filter: test.*
#    server: 127.0.0.1:11111
#    destination: example

server:
    port: 11118
spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        druid:
            username: root
            password: 123456
            url: jdbc:mysql:127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
            driverClassName: com.mysql.cj.jdbc.Driver